---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a repo
    git: 
      repo: https://nimiep:{{ password }}@github.com/nimiep/vault.git
      dest: /opt/ansadmin/test-vault
